### ISSUE TITLE
Alternative plugin collaboration suggestion

### ISSUE THREAD

**Issue by Facyla** [ColdTrick/static#15]
Hi,

I think this plugin was built for the same reasons i've worked on "cmspages" since Elgg 1.5 (limitations of externalpages), and i think i've implemented a few functionnalities that are on the "static" roadmap - maybe further actually.
I was wondering if you would be interested to check the "cmspages" plugin, and eventually contribute into it so we could gather efforts rather than leading two parallel projects.
The current version is for Elgg 1.8, but i'm planning to update much of my plugins to Elgg 1.11 by the end of the year.
There are a bunch of quite advanced functionnalities, besides "static" pages handling, it also deals with templating, generation of mini-sites, iframe export, etc. 
If you have any questions please ask, i've not documented everything so some features might not be very clear. I'm open to tweak the plugin so it can handle a larger range of uses.

You can find it here : https://github.com/Facyla/esope/tree/master/mod/cmspages
(yes most of my plugins are integrated into a global "distribution" - also master (production) branch and 1.8 branches are identical, other branches are "work in progress").

Yours,
Florian

**Comment by jdalsem** [comment]
Florian, i really like your suggestion on collaborating on this, but i think it would not be very wise at the moment. We have a client with very 'specific' needs that is pushing the development of this plugin. Therefore it could be unwise to merge these 2 projects as it could mean we run into situations where we can not agree on the path we are taking with this plugin. Feel free to borrow as much code and ideas as you need from this plugin.
